#!/bin/bash

DST='./JIS0208.swift'
SRC='./JIS0208.TXT'

HEAD="//
//  Code generated by conv.sh. DO NOT EDIT.
//
//  $(basename $DST)
//  DriversLicenseReader
//
//  Created by Qs-F on 2019/12/29.
//  Copyright © 2019 treastrain / Tanaka Ryoga. All rights reserved.
//

import Foundation

public enum JIS0208Table: String, CaseIterable {"

TAIL="\tcase x0000 = \"\"

\tpublic init(codepoint: String) {
\t\tlet cp = JIS0208Table(rawValue: codepoint)
\t\tswitch cp {
\t\tcase .some:
\t\t\tself = cp!
\t\tcase .none:
\t\t\tself = .x0000
\t\t}
\t}

\tpublic var codepoint: String {
\t\tself.rawValue
\t}
}"


PREFIX='\tcase '
INFIX=' = "'
SUFFIX='"'

echo -e "$HEAD" > $DST && cat $SRC | sed -e '/^#.*$/d' | awk '{ sub(/^0/, "\\&#", $3); sub(/$/, ";", $3); sub(/^0/, "", $2); print PREFIX $2 INFIX $3 SUFFIX }' PREFIX="$PREFIX" INFIX="$INFIX" SUFFIX="$SUFFIX" | nkf --numchar-input | sed -e 's/\\/\\\\/g' >> $DST && echo -e "$TAIL" >> $DST
